theme: jekyll-theme-minimal
defaults: 
  - scope:
      path: "" # an empty string here means all files in the project
    values: # 以下配置项也可以在任意页面自定义
      categories: "_posts"
        default:
          body:
            theme-base: theme-base-07 # 可选的主题色包括08~0f，见 <https://github.com/poole/lanyon>
            layout-reverse: true # 开启后sidebar在右边，反之左边
            sidebar-overlay: true # 开启后正文不随sidebar移动而移动
          append_to_head:
          - | # 引入live2d看板娘！不需要可以把这一项都删掉
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/gh/Dreamer-Paul/Pio@2.4/static/pio.min.css"
              />
              <script
                async="async"
                src="https://cdn.jsdelivr.net/combine/gh/Dreamer-Paul/Pio@2.4/static/l2d.min.js,gh/Dreamer-Paul/Pio@2.4/static/pio.min.js"
                onload='
                  let pio_container = document.createElement("div");
                  pio_container.classList.add("pio-container");
                  pio_container.classList.add("right");
                  pio_container.style.bottom = "-2rem";
                  pio_container.style.zIndex = "1";
                  document.body.insertAdjacentElement("beforeend", pio_container);
                  let pio_action = document.createElement("div");
                  pio_action.classList.add("pio-action");
                  pio_container.insertAdjacentElement("beforeend", pio_action);
                  let pio_canvas = document.createElement("canvas");
                  pio_canvas.id = "pio";
                  pio_canvas.style.width = "14rem";
                  pio_canvas.width = "600";
                  pio_canvas.height = "800";
                  pio_container.insertAdjacentElement("beforeend", pio_canvas);
                  let pio = new Paul_Pio({
                    "mode": "fixed",
                    "hidden": true,
                    "night": "for(let i=7; i<16; ++i) if(document.body.classList.contains(`theme-base-0`+i.toString(16))) { document.body.classList.remove(`theme-base-0`+i.toString(16)); document.body.classList.add(`theme-base-0`+((i-6)%9+7).toString(16)); break; }",
                    "content": {
                      "link": ["https:\/\/jekyll-theme-WuK.wu-kan.cn"],
                      "skin": ["要换成我的朋友吗？", "让她放个假吧~"],
                      "hidden": true,
                      "custom": [{
                        "selector": "a",
                        "type": "link",
                      }, {
                        "selector": ".sidebar-toggle",
                        "text": "打开侧边栏叭~"
                      }, {
                        "selector": ".effect-info",
                        "text": "哇，你发现了什么！"
                      }, {
                        "selector": "#sidebar-search-input",
                        "text": "想搜索什么呢？很多干货哦！"
                      }, {
                        "selector": "#toc",
                        "text": "这是目录~"
                      }, {
                        "selector": ".page-title",
                        "text": "这是标题~"
                      }, {
                        "selector": ".v",
                        "text": "评论没有审核，要对自己的发言负责哦~"
                      }]
                    },
                    "model": [
                      "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/33/model.2018.bls-winter.json",
                      "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/platelet-2/model.json",
                      "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/xiaomai/xiaomai.model.json",
                      "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/mashiro/seifuku.model.json",
                      "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/Violet/14.json",
                      "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/Kobayaxi/Kobayaxi.model.json",
                      "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/mikoto/mikoto.model.json",
                      "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/uiharu/uiharu.model.json"]
                  });'
                  ></script>